Intel Aler Lake leak checking rule
binarly-io/FwHunt pull request #7
Opened 2022-10-09 11:03 UTC by phretor

I added a rule to check if a BIOS image has been signed with leaked keys.

2022-10-10 06:18 UTC, matrosov commented
Hi Federico, could you create a new folder and move your rule there: 
`FwHunt/rules/SupplyChain/IntelAlderLakeLeak.yml`

2022-10-10 06:19 UTC, phretor commented
Yup! Makes sense.

2022-10-10 07:24 UTC, phretor commented
@matrosov done. Have a look.

2022-10-10 13:01 UTC, yeggor commented
Hi @phretor. Unfortunately in this form the rule cannot be merged. You use the rule as follows:

```bash
python fwhunt_scan_analyzer.py scan -r ../FwHunt/rules/Threats/IntelAlderLakeLeak.yml rom.bin
```

The `scan` command is only for checking EFI modules, because it will be analyzed by rizin-based analyser before being scanned. If we will use fwhunt as you do, the UefiAnalyzer from fwhunt-scan will try to analyze the whole firmware as a separate EFI module.
In order to analyze the entire firmware, we introduced the `scan-firmware` command. But to use this command, we have to specify the GUIDs of the files we want to analyze:
https://github.com/binarly-io/FwHunt/blob/cb5d688d25e65fd16009bc27674ed49260af97eb/rules/Vulnerabilities/AMI/BRLY-2022-016.yml#L10

Also, if the component you want to detect is in the compressed range, the rule will not detect anything.
If you send a sample on which the rule works for you, we'll be happy to fix it. In the meantime, it is better to use YARA:
```
rule alder_lake_leak {
  strings:
    $s1 = { 30 82 ... }
    $s2 = { 30 82 ... }
    $s3 = { 30 82 ... }
    $s4 = { 30 82 ... }
    $s5 = { 30 82 ... }
    $s6 = { 30 82 ... }
    $s7 = { 30 82 ... }
    $s8 = { 30 82 ... }
  condition:
    any of them
}
```

2022-10-10 13:08 UTC, phretor commented
>  In order to analyze the entire firmware, we introduced the scan-firmware command. But to use this command, we have to specify the GUIDs of the files we want to analyze

Is it possible to specify a "catch all" GUIDs to write such generic rules?

> Also, if the component you want to detect is in the compressed range, the rule will not detect anything.

Out of curiosity, does UEFI allow to put certs/sigs in the compressed range?

>  If you send a sample on which the rule works for you, we'll be happy to fix it.

(un)Fortunately, I still haven't found a sample affected by the leak, but I don't have much ROM images at my disposal. So I "synthetized" a test case by appending the public key (already) found in my laptop's ROM image to the rule and verified that there was a match.

2022-10-11 00:47 UTC, yeggor commented
СС @flothrone @xorpse

In fact, FwHunt was not intended as an alternative to grep or YARA. On the contrary, it was designed to detect things that are hard to detect with a byte-search (for example, we can specify which module we want to scan or only scan the SMI handler functions).

> Out of curiosity, does UEFI allow to put certs/sigs in the compressed range?

It really depends on what kind of certs/sigs we're talking about. Keys located in the `BoodGuard Key Manifest` and `BootGuard Boot Policy` will not be in the compressed range.

> (un)Fortunately, I still haven't found a sample affected by the leak, but I don't have much ROM images at my disposal. So I "synthetized" a test case by appending the public key (already) found in my laptop's ROM image to the rule and verified that there was a match.

After a closer look, we concluded that you were looking for the wrong byte patterns.
Instead of DER-formatted keys, you need to look for a public key module with a reverse byte order.
Below is the proposed YARA rule:

```
rule alder_lake_leak {
  strings:
    $s1 = { ff 84 9b 32 ff 8a 95 6b 59 49 86 8d 61 91 01 65 1a 35 ae 51 18 2a 8f 55 05 92 a8 2f f1 4e 96 40 3f 35 c2 fa d4 03 c8 f9 13 10 f0 e4 ad cf 74 7c 62 a0 80 5d 40 d8 80 2e 47 40 24 df fd 02 28 89 91 08 6a d8 18 af b8 3a 96 7d be e0 73 a9 4b 20 fa 09 57 51 e6 be 3d 43 78 c9 94 29 f5 af 93 b1 b3 03 a5 88 6b c7 d7 28 f4 51 ef f0 f2 3a 0a f9 81 2e b6 c5 5b 9b 12 75 fa eb d1 6a ce db 9f 52 b0 8a 5c e7 80 2e 09 71 12 6f a6 91 0a ce 7a 70 b1 32 84 e9 a1 2e 3f 4f 95 3d e9 3e c0 b1 94 1a 2b 7e 6f 47 c7 14 e2 d5 cb 48 1a 42 30 c8 b8 03 28 15 18 3a a3 2e 5b 19 97 14 50 63 17 6d da 64 24 85 c2 71 64 9d 6f e2 90 07 60 b5 27 c8 6f 51 6d e7 3f 5c 77 7a 29 aa 54 17 3a 2f 3b 51 d0 71 3c 4f 4c 8c ee b8 b0 bc 38 69 d5 ab a0 74 37 96 d8 f6 50 01 37 1e ea 7b b1 a1 47 2d 67 ce 5d bf }
    $s2 = { 6b ff 67 03 2a 6b 05 bc ea 29 3a 73 2a 96 56 cb 4e 41 a1 cf e5 e7 1d e2 03 02 ed 33 29 3a 76 0e d4 ed 36 9d 0c cf 37 fa fd c3 bb af 21 dd 3f 52 f3 0c 21 29 ae 0d 20 5a 26 90 10 97 c1 fd 67 dd bf 3a 93 5b 79 07 59 1e 99 ff ce 35 1e ef 3b dc da 87 8d af 25 8e 7d fc 7b 8e e6 be a0 18 4c e4 0a a6 43 79 59 61 f1 d8 c4 18 8b da b2 7b 6e 11 54 41 fb a2 f3 1a b1 a4 c9 fe cd fc 04 82 46 b8 3f e7 61 5b 27 23 9e 15 75 f4 ff a8 a4 42 fc dd d4 6c 43 60 c3 5e b8 7f f3 3d 0a a5 69 fd 28 1d 04 34 47 80 12 d2 36 fb 2e 1e e4 d8 84 06 96 2d a1 6e 5a a4 76 7d 98 2b 8e 83 46 d2 7c 3c dd 80 ab 76 f2 53 35 78 2b 32 7c 0e d9 a0 ed fe a4 bc 9a 81 14 f8 57 47 b1 e0 dc f5 a4 fd 37 06 98 a4 60 38 48 4b 2f 01 d1 3a 9a d1 6f 4f d0 07 3d 0f 2a a2 60 5d be 0c 75 8d 60 b5 6e d8 ae 2b d1 b9 }
    $s3 = { dd d5 d1 ef ba 0b 58 6e 93 3c 3d fb f7 aa 84 de ab a6 71 6c 57 74 7c 51 7b 82 43 88 4f 0f a5 dc 57 eb b2 ed e5 0c 1f 3d fe 5b 07 c9 c3 2c 8f 46 3f cb 73 85 66 74 b7 99 6d f5 67 36 66 be 1a 4e 98 90 84 f3 a5 19 b0 3f 1a 4a d2 97 51 66 ff 4c 75 09 7f 30 0b 32 8f d6 1e 87 9a 38 fb f3 41 c1 b3 4f 89 6b 1a 82 df c5 1b b2 85 7d 64 a8 e0 52 62 1e f5 7e d6 a9 e6 d3 93 9f e9 68 82 6d dc 69 e2 a1 2e 29 3a 56 9f d5 04 3c e3 3b b0 92 69 79 fa 24 07 1b b1 74 85 8d 94 1f 50 39 0f db c4 14 fd 46 69 43 4c 76 41 99 78 dd 01 9b 0c 54 96 37 76 41 cc cf 13 67 5a c5 73 db 0e 52 5c 47 d4 c8 75 ed 8a 73 74 f3 25 60 9f 7c 57 1a 95 e9 ea 0d 14 4f ad cf d6 a5 7c 01 3b 9d ae dd d0 6e 15 68 31 fc a8 33 e8 b3 fd 94 1b 28 0d 59 55 89 42 7f 9a 3e 33 1e 9f 47 b1 50 27 be 6c 96 0f 82 fe ca }
    $s4 = { ad 29 5a 8e 38 f7 79 cf b6 e2 69 3f ea b9 12 63 f0 48 34 2a 1e c2 e8 0f 7e 34 61 b3 d9 05 22 81 2c a4 f0 f4 e0 ae 02 b0 74 6c 5b 32 e7 b5 a0 84 95 8a 50 2b 1b 0c 2a cf 95 7d fa 23 56 95 d0 89 5f fa c8 24 df af 9f 17 52 8c ab 40 11 55 51 c7 1f d5 01 cb fc fa c4 cf b9 14 78 5a 87 ed a6 d7 3b 3c ab a2 04 fa 0d f8 ca 62 2f 52 94 e2 c0 2f fc 7a e3 9f d5 a7 38 b6 f2 29 09 ac 54 42 b5 e7 9d 55 6c b4 a2 cc 83 ba 55 ed 99 0c a8 18 0a 26 e0 09 a7 8a cb 0e 5e 23 43 41 6c 1b a2 28 30 05 35 01 71 bc a0 54 91 64 86 41 36 a8 ff 40 00 66 00 aa fd 42 26 4d 3c 61 4f 3b 93 35 ad 04 b5 03 0e 01 b2 9f ad a7 6b 68 7c c3 ae 6c 12 8d 48 15 86 29 64 fb 32 1a 39 94 64 61 70 78 ca 31 f6 5d 09 65 cb 08 dd 58 d9 52 d4 e3 ad 5c f7 e4 33 4f 5d 08 eb a8 85 57 ed f5 fd 6f 44 6c 17 18 a7 ba }
    $s5 = { 13 15 84 20 e2 d1 fb 84 7e 49 a7 99 4d f9 57 ef df cc 97 5b 82 38 aa 21 91 e9 8c 24 62 0d b1 63 b9 d3 4b a8 f1 e9 6b 40 8e c8 17 32 91 32 4c 25 ad e3 8a 3f 2c 77 08 1e 4f 19 55 01 12 fb 5c 90 55 e2 e5 76 42 ec c0 41 1f e7 ec 96 5f 1e ab 8f 9c 24 d6 26 90 a8 4e 3a 51 e5 14 93 1c 86 04 9b 65 74 43 8d 99 7c 79 50 31 36 e9 97 91 92 c6 6b a8 aa 4f 7d b7 7a 76 0f ba 35 21 74 b6 04 8b f5 a0 82 0c 0b 30 87 e3 2f 75 d7 2e f2 7d dc 70 e8 b2 80 7d 39 f1 c4 91 40 ec 12 5e 7a 44 5c c7 22 c7 80 9e 56 3f 99 09 35 ce 33 f8 e4 b2 5c 44 33 fd d7 3d 31 ec 21 36 fd 12 06 f1 96 78 cb ce a8 b6 4c 58 c2 b7 a8 dd ea 5d ae e5 4a 28 9b 5f 6c 8a b8 f8 69 8d 97 7a 24 1c bf 74 c5 b1 02 ea 0e 65 0b d0 d5 40 5f 6b dc 9b cf ec 40 d1 dd 6a f2 c7 29 4e b8 80 a1 6b cf 8e 3b 1c 28 40 69 e0 e4 }
    $s6 = { ff 78 7c 6e c3 d0 d9 ab af 5b 5d 5c b8 7d e3 f4 37 1b e7 2d a1 0a 9d 04 d0 7c 8e 98 5e 71 b2 09 6e d6 6f 9a c9 79 30 17 2a 97 90 6d 6e 73 16 ca 50 02 4f 2c 85 bb 49 f3 5e bf 7b 18 1c 42 0a 48 07 81 10 2a b2 bb 29 38 a2 eb c6 48 27 03 1e a5 eb 18 63 7d 76 43 be 58 58 65 c5 a1 b4 7f a4 ee 67 10 7e 45 3d ad c8 91 b9 b7 fe e8 26 a2 65 79 bc ea ab 64 02 e2 54 99 bb 89 6e 74 52 fa da 98 bf 7d ab 15 86 ad 95 af f4 ab a2 e0 dd 79 95 00 96 38 2a 63 1e 99 a2 10 dc 22 06 73 6a 4d 14 f0 d5 9a 89 8f 07 81 23 4a bb f9 fa 9f f2 01 a4 e4 c1 17 15 cb fe 47 2e 95 26 82 97 0c 39 95 dc ca 1f 59 91 19 c7 a0 5d f8 cb f6 62 74 5a 62 0d ca 35 8d 93 0c 2e 3b 12 6f 1d 8f d3 64 ac d3 c8 51 ff c7 31 94 39 25 99 43 31 07 44 86 ed 36 20 c3 aa a4 3c d4 46 0a ef 2d 1f a3 90 b8 cd cf 31 13 e0 86 7e ad 12 21 88 d2 be b3 63 4b 2c 5c e1 2c 8e cb ea 3b e7 2b f1 d4 50 c1 50 c5 7d 58 4e f5 3b 58 54 69 f1 a2 e8 6a d6 e7 b4 d2 70 c2 5a 36 fd 9b aa b1 f2 bb 3e 1d 6d e2 74 15 09 5b c0 0a 2c 05 90 59 71 eb 6f b5 9f cd fe c6 1e 9d 38 28 da 56 9d cf 05 82 69 5c 34 57 e9 8c 27 3b ae cb 4f 82 26 d3 ee 35 bd 8a 77 ad c8 39 00 8a f3 5c 2f 8e 8e f6 69 54 74 b2 23 50 17 04 0f 78 9c eb }
    $s7 = { d9 03 fc 44 eb ad 15 79 bf b1 a5 45 22 f2 af a8 6e bd b8 62 f5 4b 59 fe 6b 97 a6 9a f0 74 59 89 e2 35 27 00 74 7e 8b 10 df ef 15 84 d0 d9 a7 77 e8 af f3 7e de 4a 2a 1a 18 5f 50 ed 01 b7 4d a4 bd b4 65 a5 74 88 10 8a 22 f6 b0 c6 e6 a1 ba 64 5e d8 5e 8f fc 91 37 ef fa 88 66 56 40 1d 9a 60 43 91 dc 0b 6d 8b 01 28 4a 5b 4d b7 1f fc 0f 79 8e 92 b4 03 0b 02 b8 3b 16 ba d3 a7 f4 70 72 d8 4e e7 c0 0c 52 57 b1 05 74 c7 24 d2 6b c6 b7 5a ba 35 6e 81 0f ca 0c 46 cf 8f bb f4 8d fc 5b 3d 85 59 b0 35 7b 30 c2 10 4e 93 3c 6e cc 66 cc 2d d1 4f 5a 5e ce 73 4c 25 78 f1 73 4c e2 25 33 25 18 9c 63 9b 21 58 1f c5 6f aa 40 36 58 25 78 a4 a8 6d c5 ca 5f 95 11 d2 03 6e 00 fa 74 61 9d 2b 18 16 41 0a 3c cf 84 e8 bb b4 a7 76 d3 d9 86 2b 42 68 f3 1e 31 31 4e ad 28 ec f6 66 53 e5 26 9f c6 fa 39 6d 17 04 bf 5b d3 3e 55 24 0e b1 1f 20 90 60 8d 97 c5 b3 b7 ed dc 9f 46 9f 2f 62 5d 10 e9 80 e8 4c cc 0d 64 e0 1a b2 11 d6 03 44 24 aa 41 14 07 28 0d e3 a8 a6 e7 27 17 23 65 88 46 ed 9b de 9a c2 37 e2 2f 4f 14 3d 32 2a e2 0e 2c 41 36 7a d6 9b f1 a4 ea 8d 26 a9 a8 85 f0 56 69 00 65 88 47 ca 3b 7d 17 f6 7b e9 cb 5a 49 39 8b 41 f0 f6 5b d0 11 30 c8 92 c8 98 51 af c6 4a 76 d8 }
    $s8 = { 53 45 0f f5 91 47 0c 7d c3 d7 43 0b 3f 99 78 0d 3d 6c 87 b5 4b 32 22 4d 6a 1c a8 83 94 c4 c0 83 13 93 d9 d6 bd 5f 9c 2c 2e df 86 95 9c aa a3 69 17 c0 5e f4 2b 9e 0f c1 6c 96 6e 0f df 96 80 14 fe 51 a7 88 63 13 ea 80 48 15 d5 ed 24 9e 7d fe 17 7c 51 8c 02 3b 28 0f cf 62 d7 13 e0 48 95 fc 3b e6 7c 5f de e2 6f d3 f5 02 a6 0c 8b e9 cc ad ef e6 32 d5 38 07 ee 7e 67 87 59 05 23 9b c8 8b 84 c0 2f aa 4e 09 5c 77 8e 50 87 79 4e c6 c3 6f 39 f9 50 c8 93 5c a6 2c 4c 2e 3f 2a c3 02 5a 9c 6d 0d 4e 3e 5b 3c f8 5d c7 8d af c7 ea ad cd 2f 13 37 ff 4f 8c f3 fa e4 8b c7 b6 31 e4 64 a9 23 dd 1f 60 2f 17 a2 22 89 c2 f4 ec 56 57 28 9d 80 18 31 ee c8 4c f8 a7 90 87 e4 7a 7a fb f3 f0 85 ae 42  [...]

2022-10-11 01:15 UTC, yeggor commented
After these fixes, the rule above can be merged:
1. https://github.com/binarly-io/fwhunt-scan/commit/e3a036f3cbd576d5667c548e492dd97c245c7fe5
2. https://github.com/binarly-io/fwhunt-scan/commit/5cea7f0f03013cf4849620db7fe7604348175a87

2022-10-11 07:33 UTC, phretor commented
> СС @flothrone @xorpse
> 
> In fact, FwHunt was not intended as an alternative to grep or YARA. On the contrary, it was designed to detect things that are hard to detect with a byte-search (for example, we can specify which module we want to scan or only scan the SMI handler functions).

Ou yes :-) I'm aware of FwHunt/efiXplorer's unique scope and my first thought was also to create a `grep`-based checker (*). But once I was done with that I thought: wait, what's the first thing that comes to mind to check if a firmware has issues? I knew that FwHunt was a bit of a stretch for the task, but I think that FwHunt sees more firmware images passing under it than Yara does, globally.

I didn't think of Yara because I'm not sure how much it's used in firmware DFIR tasks, but to be honest I don't have data to back my position.

(*) = thanks for fixing my naïve patterns..eh!

> > Out of curiosity, does UEFI allow to put certs/sigs in the compressed range?
> 
> It really depends on what kind of certs/sigs we're talking about. Keys located in the `BoodGuard Key Manifest` and `BootGuard Boot Policy` will not be in the compressed range.
> 
> > (un)Fortunately, I still haven't found a sample affected by the leak, but I don't have much ROM images at my disposal. So I "synthetized" a test case by appending the public key (already) found in my laptop's ROM image to the rule and verified that there was a match.
> 
> After a closer look, we concluded that you were looking for the wrong byte patterns. Instead of DER-formatted keys, you need to look for a public key module with a reverse byte order. Below is the proposed YARA rule:

Do you happen to have a firmware image (that you can somehow share) that matches these patterns? It'll be very helpful as a learning example to me. I'll see if VT has something in the meanwhile.

> ```
> rule alder_lake_leak {
>   8<-------8<-----------------------------------------
>   condition:
>     any of them
> }
> ```
> 
> If you are still interested in adding a fwhunt rule, we can do it as follows:
> 
> ```
> IntelAlderLakeLeak:
>   meta:
>     author: Federico Maggi (https://twitter.com/phretor)
>     license: CC0-1.0
>     name: IntelAlderLakeLeak
>     namespace: SupplyChain
>     description: BIOS image signed with leaked private keys
>     url: https://github.com/phretor/intel-leak-checker/
>     target: firmware # so that fwhunt-scan does not try to analyze the entire firmware
>   hex_strings:
>     or:
>   8<-------8<-----------------------------------------
> ```

Thanks! I'll check the changes you pushed in FwHunt.

2022-10-11 12:02 UTC, yeggor requested changes

2022-10-11 12:02 UTC, yeggor commented on rules/SupplyChain/IntelAlderLakeLeak.yml
> +    namespace: IntelAlderLakeLeak
SupplyChain

2022-10-11 12:07 UTC, phretor reviewed
Renamed

2022-10-11 12:08 UTC, phretor reviewed
Done.

2022-10-11 12:10 UTC, phretor commented
Done here https://github.com/binarly-io/FwHunt/commit/6c745ad5d04006f931186a0e2bde194c40da1d9c

2022-10-11 12:22 UTC, yeggor approved these changes

2022-10-11 12:22 UTC, merged

2022-10-11 12:25 UTC, yeggor commented
> Do you happen to have a firmware image (that you can somehow share) that matches these patterns? It'll be very helpful as a learning example to me. I'll see if VT has something in the meanwhile.

It might be a good idea to look in the same place where you found the keys.

Thanks a lot you for your contribution!

2022-10-11 12:34 UTC, phretor commented
> It might be a good idea to look in the same place where you found the keys.

Ah, of course. That's the easiest place to look. I was so convinced that that was source code that I didn't even think of checking for binaries 😄 

Thanks to you for your debugging!